name: docs
on: [ push, workflow_dispatch ]
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Run Dokka Task
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: true
          arguments: dokkaHtml

      - name: Deploy Documentations
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/dokka/html